import { useState, useEffect } from 'react'
import { useParams, useNavigate, Link } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import { projectAPI, generateAIPreview, deleteAIPreview } from '../../services/api'
import JSZip from 'jszip'
import Header from '../Header/Header'
import './ProjectDetail.css'

const MAX_PREVIEWS_PER_PROJECT = 5

const ProjectDetail = () => {
  const { id } = useParams()
  const navigate = useNavigate()
  const { user } = useAuth()
  const [project, setProject] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [updating, setUpdating] = useState(false)
  const [markingReady, setMarkingReady] = useState(false)
  const [previews, setPreviews] = useState([])
  const [previewsLoading, setPreviewsLoading] = useState(false)
  const [showGenerateForm, setShowGenerateForm] = useState(false)
  const [generateFormData, setGenerateFormData] = useState({
    prompt: '',
    budget: '',
    timeline: '',
    projectType: '',
    techStack: ''
  })
  const [generating, setGenerating] = useState(false)
  const [generateError, setGenerateError] = useState('')
  const [expandedPreviewId, setExpandedPreviewId] = useState(null)
  const [copySuccessId, setCopySuccessId] = useState(null)
  const [showMoreDetails, setShowMoreDetails] = useState(false)

  useEffect(() => {
    if (!id || id === 'undefined') {
      navigate('/projects', { replace: true })
      return
    }
    loadProject()
  }, [id, navigate])

  useEffect(() => {
    if (project && id) {
      loadPreviews()
    }
  }, [id, project?._id])

  const loadProject = async () => {
    try {
      setLoading(true)
      setError(null)
      const data = await projectAPI.getById(id)
      setProject(data)
    } catch (err) {
      setError(err.response?.data?.message || err.message || 'Failed to load project')
    } finally {
      setLoading(false)
    }
  }

  const loadPreviews = async () => {
    try {
      setPreviewsLoading(true)
      const data = await projectAPI.getPreviews(id)
      setPreviews(data)
    } catch (err) {
      console.error('Failed to load previews', err)
      setPreviews([])
    } finally {
      setPreviewsLoading(false)
    }
  }

  const handleMarkReady = async () => {
    if (!window.confirm('Mark this project as Ready for assignment?')) {
      return
    }

    try {
      setMarkingReady(true)
      setError(null)
      const updatedProject = await projectAPI.markReady(id)
      setProject(updatedProject)
    } catch (err) {
      setError(err.response?.data?.message || err.message || 'Failed to mark project as ready')
    } finally {
      setMarkingReady(false)
    }
  }

  const handleDelete = async () => {
    if (!window.confirm('Are you sure you want to delete this project? This action cannot be undone.')) {
      return
    }

    try {
      await projectAPI.delete(id)
      navigate('/projects')
    } catch (err) {
      setError(err.response?.data?.message || err.message || 'Failed to delete project')
    }
  }

  const handleGenerateSubmit = async (e) => {
    e.preventDefault()
    if (!generateFormData.prompt.trim()) {
      setGenerateError('Please describe your project')
      return
    }
    setGenerating(true)
    setGenerateError('')
    try {
      await generateAIPreview({ ...generateFormData, projectId: id })
      await loadPreviews()
      setShowGenerateForm(false)
      setGenerateFormData({ prompt: '', budget: '', timeline: '', projectType: '', techStack: '' })
    } catch (err) {
      setGenerateError(err.message || 'Failed to generate preview')
    } finally {
      setGenerating(false)
    }
  }

  const handleDeletePreview = async (previewId) => {
    if (!window.confirm('Delete this AI preview?')) return
    try {
      await deleteAIPreview(previewId)
      await loadPreviews()
    } catch (err) {
      setError(err.message || 'Failed to delete preview')
    }
  }

  const handleCopyPreviewCode = async (previewId, code) => {
    if (!code) return
    try {
      await navigator.clipboard.writeText(code)
      setCopySuccessId(previewId)
      setTimeout(() => setCopySuccessId(null), 2000)
    } catch (err) {
      console.error('Failed to copy', err)
    }
  }

  const handleDownloadPreviewCode = async (code) => {
    if (!code) return
    try {
      const zip = new JSZip()
      zip.file('App.js', code)
      zip.file('package.json', JSON.stringify({
        name: 'generated-react-component',
        version: '1.0.0',
        private: true,
        dependencies: { react: '^18.2.0', 'react-dom': '^18.2.0', 'react-scripts': '5.0.1' },
        scripts: { start: 'react-scripts start', build: 'react-scripts build' }
      }, null, 2))
      zip.file('README.md', '# Generated by Chapadevs AI\n\nnpm install\nnpm start')
      const blob = await zip.generateAsync({ type: 'blob' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = 'react-component.zip'
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error('Failed to download', err)
    }
  }

  const getStatusBadgeClass = (status) => {
    const statusMap = {
      'Holding': 'status-holding',
      'Ready': 'status-ready',
      'Development': 'status-development',
      'Completed': 'status-completed',
      'Cancelled': 'status-cancelled',
    }
    return statusMap[status] || 'status-default'
  }

  if (loading) {
    return <div className="project-detail-loading">Loading project...</div>
  }

  if (error && !project) {
    return (
      <div className="project-detail-container">
        <div className="error-message">{error}</div>
        <Link to="/projects" className="project-detail-back">← Back to Projects</Link>
      </div>
    )
  }

  if (!project) {
    return <div className="project-detail-container">Project not found</div>
  }

  const userIdStr = (user?._id || user?.id)?.toString()
  const clientIdStr = (project.clientId?._id || project.clientId)?.toString()
  const assignedProgrammerIdStr = (project.assignedProgrammerId?._id || project.assignedProgrammerId)?.toString()
  const isClientOwner = userIdStr && clientIdStr && clientIdStr === userIdStr
  const isAssignedProgrammer = userIdStr && assignedProgrammerIdStr && assignedProgrammerIdStr === userIdStr
  const canEdit = (user?.role === 'client' || user?.role === 'user') && isClientOwner && ['Holding', 'Ready'].includes(project.status)
  const canDelete = (user?.role === 'client' || user?.role === 'user') && isClientOwner && project.status === 'Holding'
  const canMarkReady = (user?.role === 'client' || user?.role === 'user') && isClientOwner && project.status === 'Holding'
  const canGeneratePreviews = isClientOwner && previews.length < MAX_PREVIEWS_PER_PROJECT
  const showAIPreviewsSection = isClientOwner || isAssignedProgrammer

  const parsePreviewResult = (previewResult) => {
    if (!previewResult) return null
    try {
      return JSON.parse(previewResult)
    } catch {
      return { raw: previewResult }
    }
  }

  const buildPreviewIframeSrcDoc = (websiteCode) => {
    if (!websiteCode) return ''
    let code = websiteCode
    code = code.replace(/```jsx?\n?/g, '').replace(/```\n?/g, '')
    code = code.replace(/function\s+App\s*\(\)\s*=>/g, 'function App()')
    code = code.replace(/const GeneratedComponent\s*=\s*\(\)\s*=>/g, 'function App()')
    code = code.replace(/const GeneratedComponent\s*=/g, 'function App')
    code = code.replace(/export default GeneratedComponent;?/g, 'export default App;')
    code = code.replace(/export default function GeneratedComponent\(\)/g, 'export default function App()')
    code = code.replace(/function GeneratedComponent\(\)/g, 'function App()')
    code = code.replace(/GeneratedComponent/g, 'App')
    if (!code.includes('export default App')) {
      code = code.replace(/export default \w+;?/g, 'export default App;')
    }
    const componentMatch = code.match(/(?:function|const)\s+App\s*[=\(].*?export default App/s)
    let componentCode = code
    if (componentMatch) {
      componentCode = componentMatch[0].replace(/export default App;?/g, '')
    }
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Preview</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <style>body{margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;}</style>
</head>
<body>
  <div id="root"></div>
  <script type="text/babel">
    const { useState } = React;
    ${componentCode}
    const AppComponent = App;
    const root = ReactDOM.createRoot(document.getElementById('root'));
    root.render(React.createElement(AppComponent));
  </script>
</body>
</html>`
  }

  const renderPreviewAnalysis = (preview) => {
    const result = parsePreviewResult(preview.previewResult)
    if (!result) return <p className="project-preview-empty">No analysis content.</p>
    if (result.raw) return <p className="project-preview-analysis">{result.raw}</p>
    const tech = result.techStack
    const frontend = Array.isArray(tech?.frontend) ? tech.frontend : []
    const backend = Array.isArray(tech?.backend) ? tech.backend : []
    return (
      <div className="project-preview-analysis">
        {result.overview && <p><strong>Overview:</strong> {result.overview}</p>}
        {result.features?.length > 0 && (
          <div>
            <strong>Features:</strong>
            <ul>{result.features.map((f, i) => <li key={i}>{f}</li>)}</ul>
          </div>
        )}
        {(frontend.length > 0 || backend.length > 0) && (
          <div>
            <strong>Tech stack:</strong>
            {frontend.length > 0 && <p><strong>Frontend:</strong> {frontend.join(', ')}</p>}
            {backend.length > 0 && <p><strong>Backend:</strong> {backend.join(', ')}</p>}
          </div>
        )}
      </div>
    )
  }

  return (
    <>
      <Header />
      <div className="project-detail-container">
      <div className="project-detail-header">
        <div>
          <Link to="/projects" className="project-detail-back">← Back to Projects</Link>
          <h1>{project.title}</h1>
          <div className="project-header-meta">
            <span className={`status-badge ${getStatusBadgeClass(project.status)}`}>
              {project.status}
            </span>
          </div>
        </div>
        <div className="project-actions">
          {canMarkReady && (
            <button
              onClick={handleMarkReady}
              className="btn btn-primary"
              disabled={markingReady}
            >
              {markingReady ? 'Marking...' : 'Mark as Ready'}
            </button>
          )}
          {canDelete && (
            <button onClick={handleDelete} className="btn btn-danger">
              Delete Project
            </button>
          )}
        </div>
      </div>

      {error && <div className="error-message">{error}</div>}

      <div className="project-detail-content">
        <div className="project-main">
          <section className="project-section project-overview">
            {project.projectType && (
              <span className="project-overview-type">{project.projectType}</span>
            )}
            <p className="project-overview-description">{project.description}</p>
            {(project.goals?.length > 0 || project.features?.length > 0 || project.technologies?.length > 0) && (
              <div className="project-overview-meta">
                <span className="project-overview-badges">
                  {project.goals?.length > 0 && (
                    <span className="project-overview-tag">Goals: {project.goals.join(' · ')}</span>
                  )}
                  {project.features?.length > 0 && (
                    <span className="project-overview-tag">Features: {project.features.join(' · ')}</span>
                  )}
                  {project.technologies?.length > 0 && (
                    <span className="project-overview-tag">Tech: {project.technologies.join(', ')}</span>
                  )}
                </span>
              </div>
            )}
            {(project.brandingDetails || project.specialRequirements || project.additionalComments) && (
              <div className="project-more-details">
                <button
                  type="button"
                  className="project-more-details-toggle"
                  onClick={() => setShowMoreDetails((v) => !v)}
                  aria-expanded={showMoreDetails}
                >
                  {showMoreDetails ? '▼ Hide details' : '▶ More details'}
                </button>
                {showMoreDetails && (
                  <div className="project-more-details-content">
                    {project.brandingDetails && (
                      <div className="project-more-detail-row">
                        <strong>Branding:</strong> {project.hasBranding && `${project.hasBranding} — `}
                        {project.brandingDetails}
                      </div>
                    )}
                    {project.specialRequirements && (
                      <div className="project-more-detail-row">
                        <strong>Special requirements:</strong> {project.specialRequirements}
                      </div>
                    )}
                    {project.additionalComments && (
                      <div className="project-more-detail-row">
                        <strong>Comments:</strong> {project.additionalComments}
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}
          </section>

          {showAIPreviewsSection && (
            <section className="project-section project-section-previews">
              <h2>AI Previews</h2>
              <p className="project-previews-intro">
                {previews.length} / {MAX_PREVIEWS_PER_PROJECT} previews.
                {isClientOwner && ' Generate up to 5 AI previews for this project. Programmers can view and use the code once assigned.'}
                {isAssignedProgrammer && !isClientOwner && ' View and download the client’s generated preview code to start development.'}
              </p>

              {isClientOwner && canGeneratePreviews && !showGenerateForm && (
                <button
                  type="button"
                  className="btn btn-primary project-generate-preview-btn"
                  onClick={() => setShowGenerateForm(true)}
                >
                  Generate new preview
                </button>
              )}

              {showGenerateForm && (
                <form onSubmit={handleGenerateSubmit} className="project-preview-form">
                  <div className="project-preview-form-group">
                    <label htmlFor="preview-prompt">Project description *</label>
                    <textarea
                      id="preview-prompt"
                      value={generateFormData.prompt}
                      onChange={(e) => setGenerateFormData({ ...generateFormData, prompt: e.target.value })}
                      placeholder="Describe the preview you want..."
                      rows={3}
                      required
                    />
                  </div>
                  <div className="project-preview-form-row">
                    <div className="project-preview-form-group">
                      <label htmlFor="preview-budget">Budget</label>
                      <select
                        id="preview-budget"
                        value={generateFormData.budget}
                        onChange={(e) => setGenerateFormData({ ...generateFormData, budget: e.target.value })}
                      >
                        <option value="">Select...</option>
                        <option value="Under $5,000">Under $5,000</option>
                        <option value="$5,000 - $10,000">$5,000 - $10,000</option>
                        <option value="$10,000 - $25,000">$10,000 - $25,000</option>
                        <option value="$25,000+">$25,000+</option>
                      </select>
                    </div>
                    <div className="project-preview-form-group">
                      <label htmlFor="preview-timeline">Timeline</label>
                      <select
                        id="preview-timeline"
                        value={generateFormData.timeline}
                        onChange={(e) => setGenerateFormData({ ...generateFormData, timeline: e.target.value })}
                      >
                        <option value="">Select...</option>
                        <option value="1-2 weeks">1-2 weeks</option>
                        <option value="2-4 weeks">2-4 weeks</option>
                        <option value="1-2 months">1-2 months</option>
                        <option value="2-3 months">2-3 months</option>
                      </select>
                    </div>
                  </div>
                  <div className="project-preview-form-group">
                    <label htmlFor="preview-tech">Tech preferences (optional)</label>
                    <input
                      id="preview-tech"
                      type="text"
                      value={generateFormData.techStack}
                      onChange={(e) => setGenerateFormData({ ...generateFormData, techStack: e.target.value })}
                      placeholder="e.g. React, Node.js"
                    />
                  </div>
                  {generateError && <div className="error-message">{generateError}</div>}
                  <div className="project-preview-form-actions">
                    <button type="submit" className="btn btn-primary" disabled={generating}>
                      {generating ? 'Generating...' : 'Generate preview'}
                    </button>
                    <button
                      type="button"
                      className="btn btn-secondary"
                      onClick={() => { setShowGenerateForm(false); setGenerateError(''); }}
                    >
                      Cancel
                    </button>
                  </div>
                </form>
              )}

              {previewsLoading ? (
                <p className="project-previews-loading">Loading previews...</p>
              ) : previews.length === 0 ? (
                <p className="project-previews-empty">No AI previews yet. {isClientOwner && 'Generate one above.'}</p>
              ) : (
                <div className="project-previews-list">
                  {previews.map((preview) => {
                    const previewId = preview._id || preview.id
                    const isExpanded = expandedPreviewId === previewId
                    const code = preview.metadata?.websitePreviewCode || ''
                    return (
                      <div key={previewId} className="project-preview-card">
                        <div
                          className="project-preview-card-header"
                          onClick={() => setExpandedPreviewId(isExpanded ? null : previewId)}
                          role="button"
                          tabIndex={0}
                          onKeyDown={(e) => e.key === 'Enter' && setExpandedPreviewId(isExpanded ? null : previewId)}
                        >
                          <span className="project-preview-date">
                            {new Date(preview.createdAt).toLocaleString()}
                          </span>
                          <span className="project-preview-prompt">
                            {preview.prompt?.substring(0, 80)}{preview.prompt?.length > 80 ? '...' : ''}
                          </span>
                          <span className={`project-preview-status project-preview-status--${preview.status}`}>
                            {preview.status}
                          </span>
                          <span className="project-preview-expand">{isExpanded ? '▼' : '▶'}</span>
                        </div>
                        {isExpanded && (
                          <div className="project-preview-card-body">
                            <div className="project-preview-tabs">
                              <h4>Analysis</h4>
                              {renderPreviewAnalysis(preview)}
                            </div>
                            {code && (
                              <>
                                <div className="project-preview-iframe-block">
                                  <h4>Website Preview</h4>
                                  <div className="project-preview-iframe-wrap">
                                    <iframe
                                      title="Website Preview"
                                      sandbox="allow-scripts allow-same-origin"
                                      srcDoc={buildPreviewIframeSrcDoc(code)}
                                      className="project-preview-iframe"
                                    />
                                  </div>
                                  <div className="project-preview-code-actions">
                                    <button
                                      type="button"
                                      className="btn btn-secondary btn-sm"
                                      onClick={() => handleCopyPreviewCode(previewId, code)}
                                    >
                                      {copySuccessId === previewId ? 'Copied!' : 'Copy code'}
                                    </button>
                                    <button
                                      type="button"
                                      className="btn btn-secondary btn-sm"
                                      onClick={() => handleDownloadPreviewCode(code)}
                                    >
                                      Download ZIP
                                    </button>
                                  </div>
                                </div>
                              </>
                            )}
                            {isClientOwner && (
                              <button
                                type="button"
                                className="btn btn-danger btn-sm project-preview-delete"
                                onClick={() => handleDeletePreview(previewId)}
                              >
                                Delete preview
                              </button>
                            )}
                          </div>
                        )}
                      </div>
                    )
                  })}
                </div>
              )}
            </section>
          )}
        </div>

        <div className="project-sidebar">
          <section className="project-info-card">
            <h3>Project Information</h3>
            <div className="info-item">
              <strong>Client:</strong>
              <span>{project.clientId?.name ?? 'N/A'}</span>
            </div>
            {project.assignedProgrammerId && (
              <div className="info-item">
                <strong>Assigned Programmer:</strong>
                <span>{project.assignedProgrammerId.name}</span>
              </div>
            )}
            {project.budget && (
              <div className="info-item">
                <strong>Budget:</strong>
                <span>{project.budget}</span>
              </div>
            )}
            {project.timeline && (
              <div className="info-item">
                <strong>Timeline:</strong>
                <span>{project.timeline}</span>
              </div>
            )}
            {project.startDate && (
              <div className="info-item">
                <strong>Start Date:</strong>
                <span>{new Date(project.startDate).toLocaleDateString()}</span>
              </div>
            )}
            {project.dueDate && (
              <div className="info-item">
                <strong>Due Date:</strong>
                <span>{new Date(project.dueDate).toLocaleDateString()}</span>
              </div>
            )}
            <div className="info-item">
              <strong>Created:</strong>
              <span>{new Date(project.createdAt).toLocaleDateString()}</span>
            </div>
          </section>
        </div>
      </div>
      </div>
    </>
  )
}

export default ProjectDetail

