import AIPreview from '../models/AIPreview.js'
import Project from '../models/Project.js'
import asyncHandler from 'express-async-handler'

// @desc    Generate AI preview
// @route   POST /api/ai-previews
// @access  Private
export const generateAIPreview = asyncHandler(async (req, res) => {
  const { prompt, projectId, previewType } = req.body

  if (!prompt) {
    res.status(400)
    throw new Error('Please provide a prompt for the AI preview')
  }

  // If projectId is provided, verify it belongs to the user
  if (projectId) {
    const project = await Project.findByPk(projectId)
    if (!project || project.clientId !== req.user.id) {
      res.status(403)
      throw new Error('Not authorized to generate preview for this project')
    }
  }

  // Create preview record with generating status
  const preview = await AIPreview.create({
    userId: req.user.id,
    projectId: projectId || null,
    prompt,
    previewType: previewType || 'text',
    previewResult: '', // Will be updated when AI generates
    status: 'generating'
  })

  // TODO: Integrate with actual AI service (OpenAI, etc.)
  // For now, simulate AI generation
  setTimeout(async () => {
    const mockResult = `AI Preview Result for: "${prompt}"\n\nThis is a generated preview based on your requirements. In production, this would be generated by an AI service.`
    
    await preview.update({
      previewResult: mockResult,
      status: 'completed'
    })
  }, 2000)

  res.status(201).json({
    id: preview.id,
    prompt: preview.prompt,
    previewType: preview.previewType,
    status: preview.status,
    message: 'AI preview generation started. Check back in a few seconds.'
  })
})

// @desc    Get all AI previews for current user
// @route   GET /api/ai-previews
// @access  Private
export const getAIPreviews = asyncHandler(async (req, res) => {
  const previews = await AIPreview.findAll({
    where: { userId: req.user.id },
    include: [
      {
        association: 'project',
        attributes: ['id', 'title', 'status'],
        required: false
      }
    ],
    order: [['createdAt', 'DESC']]
  })

  res.json(previews)
})

// @desc    Get AI preview by ID
// @route   GET /api/ai-previews/:id
// @access  Private
export const getAIPreviewById = asyncHandler(async (req, res) => {
  const preview = await AIPreview.findByPk(req.params.id, {
    include: [
      {
        association: 'project',
        attributes: ['id', 'title', 'status'],
        required: false
      }
    ]
  })

  if (!preview) {
    res.status(404)
    throw new Error('AI preview not found')
  }

  // Verify ownership
  if (preview.userId !== req.user.id && req.user.role !== 'admin') {
    res.status(403)
    throw new Error('Not authorized to view this preview')
  }

  res.json(preview)
})

// @desc    Delete AI preview
// @route   DELETE /api/ai-previews/:id
// @access  Private
export const deleteAIPreview = asyncHandler(async (req, res) => {
  const preview = await AIPreview.findByPk(req.params.id)

  if (!preview) {
    res.status(404)
    throw new Error('AI preview not found')
  }

  // Verify ownership
  if (preview.userId !== req.user.id && req.user.role !== 'admin') {
    res.status(403)
    throw new Error('Not authorized to delete this preview')
  }

  await preview.destroy()

  res.json({ message: 'AI preview deleted successfully' })
})

