steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_BACKEND_URL=${_VITE_BACKEND_URL}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/chapadevs-frontend/chapadevs-frontend:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chapadevs-frontend'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/chapadevs-frontend/chapadevs-frontend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '256Mi'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/chapadevs-frontend/chapadevs-frontend:$COMMIT_SHA'

substitutions:
  _REGION: us-east4
  _VITE_BACKEND_URL: ''
