import { useState } from 'react'
import { generateAIPreview } from '../../services/api'
import { Sandpack } from '@codesandbox/sandpack-react'
import './AIPreviewGenerator.css'

const AIPreviewGenerator = () => {
  const [formData, setFormData] = useState({
    prompt: '',
    budget: '',
    timeline: '',
    projectType: '',
    techStack: ''
  })
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [websitePreview, setWebsitePreview] = useState(null)
  const [error, setError] = useState('')
  const [activeTab, setActiveTab] = useState('analysis')
  const [copySuccess, setCopySuccess] = useState(false)

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    })
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    
    if (!formData.prompt.trim()) {
      setError('Please describe your project')
      return
    }

    setLoading(true)
    setError('')
    setResult(null)
    setWebsitePreview(null)

    try {
      const response = await generateAIPreview(formData)
      
      // Parse the JSON result if it's a string
      let parsedResult
      if (typeof response.result === 'string') {
        try {
          parsedResult = JSON.parse(response.result)
        } catch {
          // If it's not JSON, keep as is
          parsedResult = { raw: response.result }
        }
      } else {
        parsedResult = response.result
      }

      setResult({
        ...parsedResult,
        fromCache: response.fromCache,
        tokenUsage: response.tokenUsage
      })

      // Set website preview if available
      if (response.websitePreview && response.websitePreview.htmlCode) {
        setWebsitePreview(response.websitePreview.htmlCode)
      }
    } catch (err) {
      setError(err.message || 'Failed to generate AI preview. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  const handleCopyCode = async () => {
    if (!websitePreview) return
    
    try {
      await navigator.clipboard.writeText(websitePreview)
      setCopySuccess(true)
      setTimeout(() => setCopySuccess(false), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  const handleDownloadCode = async () => {
    if (!websitePreview) return
    
    try {
      // Dynamically import JSZip
      const JSZip = (await import('jszip')).default
      const zip = new JSZip()
      
      // Add files to zip
      zip.file('App.js', websitePreview)
      zip.file('package.json', JSON.stringify({
        name: 'generated-react-component',
        version: '1.0.0',
        private: true,
        dependencies: {
          'react': '^18.2.0',
          'react-dom': '^18.2.0',
          'react-scripts': '5.0.1'
        },
        scripts: {
          'start': 'react-scripts start',
          'build': 'react-scripts build'
        }
      }, null, 2))
      
      zip.file('README.md', `# Generated React Component

This component was generated by Chapadevs AI.

## Installation

\`\`\`bash
npm install
\`\`\`

## Run

\`\`\`bash
npm start
\`\`\`
`)
      
      // Generate and download
      const blob = await zip.generateAsync({ type: 'blob' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = 'react-component.zip'
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error('Failed to download:', err)
      setError('Failed to download code. Please try again.')
    }
  }

  const renderResult = () => {
    if (!result) return null

    // If it's a raw text result
    if (result.raw) {
      return (
        <div className="ai-result-section">
          <div className="result-header">
            <h3>AI Analysis</h3>
            {result.fromCache && <span className="cache-badge">From Cache</span>}
          </div>
          <div className="result-content">
            <pre>{result.raw}</pre>
          </div>
        </div>
      )
    }

    // Structured JSON result
    return (
      <div className="ai-results">
        <div className="result-header">
          <h3>AI Project Analysis</h3>
          <div className="result-badges">
            {result.fromCache && <span className="cache-badge">⚡ From Cache</span>}
            {result.tokenUsage && <span className="token-badge">~{result.tokenUsage} tokens</span>}
          </div>
        </div>

        {result.title && (
          <div className="result-section title-section">
            <h2>{result.title}</h2>
          </div>
        )}

        {result.overview && (
          <div className="result-section">
            <h4>📋 Project Overview</h4>
            <p>{result.overview}</p>
          </div>
        )}

        {result.features && result.features.length > 0 && (
          <div className="result-section">
            <h4>✨ Key Features</h4>
            <ul className="features-list">
              {result.features.map((feature, index) => (
                <li key={index}>{feature}</li>
              ))}
            </ul>
          </div>
        )}

        {result.techStack && (
          <div className="result-section">
            <h4>🛠️ Technology Stack</h4>
            <div className="tech-stack-grid">
              {result.techStack.frontend && (
                <div className="tech-category">
                  <h5>Frontend</h5>
                  <ul>
                    {result.techStack.frontend.map((tech, index) => (
                      <li key={index}>{tech}</li>
                    ))}
                  </ul>
                </div>
              )}
              {result.techStack.backend && (
                <div className="tech-category">
                  <h5>Backend</h5>
                  <ul>
                    {result.techStack.backend.map((tech, index) => (
                      <li key={index}>{tech}</li>
                    ))}
                  </ul>
                </div>
              )}
              {result.techStack.database && (
                <div className="tech-category">
                  <h5>Database</h5>
                  <ul>
                    {result.techStack.database.map((tech, index) => (
                      <li key={index}>{tech}</li>
                    ))}
                  </ul>
                </div>
              )}
              {result.techStack.deployment && (
                <div className="tech-category">
                  <h5>Deployment</h5>
                  <ul>
                    {result.techStack.deployment.map((tech, index) => (
                      <li key={index}>{tech}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </div>
        )}

        {result.timeline && (
          <div className="result-section">
            <h4>📅 Project Timeline ({result.timeline.totalWeeks} weeks)</h4>
            <div className="timeline-phases">
              {result.timeline.phases && result.timeline.phases.map((phase, index) => (
                <div key={index} className="timeline-phase">
                  <div className="phase-header">
                    <strong>{phase.phase}</strong>
                    <span className="phase-duration">{phase.weeks} weeks</span>
                  </div>
                  {phase.deliverables && (
                    <ul className="deliverables">
                      {phase.deliverables.map((deliverable, idx) => (
                        <li key={idx}>{deliverable}</li>
                      ))}
                    </ul>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {result.budgetBreakdown && (
          <div className="result-section">
            <h4>💰 Budget Breakdown</h4>
            <p className="budget-total">Total: {result.budgetBreakdown.total}</p>
            <div className="budget-items">
              {result.budgetBreakdown.breakdown && result.budgetBreakdown.breakdown.map((item, index) => (
                <div key={index} className="budget-item">
                  <div className="budget-item-header">
                    <span className="budget-category">{item.category}</span>
                    <span className="budget-percentage">{item.percentage}%</span>
                  </div>
                  <p className="budget-description">{item.description}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {result.risks && result.risks.length > 0 && (
          <div className="result-section">
            <h4>⚠️ Risk Assessment</h4>
            <ul className="risks-list">
              {result.risks.map((risk, index) => (
                <li key={index}>{risk}</li>
              ))}
            </ul>
          </div>
        )}

        {result.recommendations && result.recommendations.length > 0 && (
          <div className="result-section">
            <h4>💡 Recommendations</h4>
            <ul className="recommendations-list">
              {result.recommendations.map((rec, index) => (
                <li key={index}>{rec}</li>
              ))}
            </ul>
          </div>
        )}
      </div>
    )
  }

  return (
    <div className="ai-preview-generator">
      <div className="generator-header">
        <h3>AI Project Preview Generator</h3>
        <p className="generator-subtitle">
          Get instant project analysis powered by AI (5 generations per hour)
        </p>
      </div>

      <form onSubmit={handleSubmit} className="generator-form">
        <div className="form-group">
          <label htmlFor="prompt">Project Description *</label>
          <textarea
            id="prompt"
            name="prompt"
            value={formData.prompt}
            onChange={handleChange}
            placeholder="Describe your project idea... (e.g., 'I need an e-commerce website for selling handmade crafts with payment integration')"
            rows="4"
            required
          />
        </div>

        <div className="form-row">
          <div className="form-group">
            <label htmlFor="projectType">Project Type</label>
            <select
              id="projectType"
              name="projectType"
              value={formData.projectType}
              onChange={handleChange}
            >
              <option value="">Select type...</option>
              <option value="New Website Design & Development">New Website</option>
              <option value="Website Redesign/Refresh">Website Redesign</option>
              <option value="E-commerce Store">E-commerce</option>
              <option value="Landing Page">Landing Page</option>
              <option value="Web Application">Web Application</option>
              <option value="Mobile App">Mobile App</option>
              <option value="Other">Other</option>
            </select>
          </div>

          <div className="form-group">
            <label htmlFor="budget">Budget</label>
            <select
              id="budget"
              name="budget"
              value={formData.budget}
              onChange={handleChange}
            >
              <option value="">Select budget...</option>
              <option value="Under $5,000">Under $5,000</option>
              <option value="$5,000 - $10,000">$5,000 - $10,000</option>
              <option value="$10,000 - $25,000">$10,000 - $25,000</option>
              <option value="$25,000 - $50,000">$25,000 - $50,000</option>
              <option value="$50,000+">$50,000+</option>
            </select>
          </div>
        </div>

        <div className="form-row">
          <div className="form-group">
            <label htmlFor="timeline">Timeline</label>
            <select
              id="timeline"
              name="timeline"
              value={formData.timeline}
              onChange={handleChange}
            >
              <option value="">Select timeline...</option>
              <option value="1-2 weeks">1-2 weeks</option>
              <option value="2-4 weeks">2-4 weeks</option>
              <option value="1-2 months">1-2 months</option>
              <option value="2-3 months">2-3 months</option>
              <option value="3-6 months">3-6 months</option>
              <option value="6+ months">6+ months</option>
            </select>
          </div>

          <div className="form-group">
            <label htmlFor="techStack">Tech Preferences (Optional)</label>
            <input
              type="text"
              id="techStack"
              name="techStack"
              value={formData.techStack}
              onChange={handleChange}
              placeholder="e.g., React, Node.js, MongoDB"
            />
          </div>
        </div>

        {error && <div className="error-message">{error}</div>}

        <button type="submit" className="generate-button" disabled={loading}>
          {loading ? (
            <>
              <span className="spinner"></span>
              Generating Analysis...
            </>
          ) : (
            'Generate Project Preview'
          )}
        </button>
      </form>

      {loading && (
        <div className="loading-state">
          <div className="loading-spinner"></div>
          <p>Analyzing your project requirements with AI...</p>
          <p className="loading-subtext">This may take 30-60 seconds</p>
        </div>
      )}

      {(result || websitePreview) && (
        <div className="results-container">
          <div className="results-tabs">
            <button 
              className={`tab-button ${activeTab === 'analysis' ? 'active' : ''}`}
              onClick={() => setActiveTab('analysis')}
            >
              📋 Project Analysis
            </button>
            {websitePreview && (
              <button 
                className={`tab-button ${activeTab === 'preview' ? 'active' : ''}`}
                onClick={() => setActiveTab('preview')}
              >
                🌐 Website Preview
              </button>
            )}
          </div>

          {activeTab === 'analysis' && renderResult()}
          
          {activeTab === 'preview' && websitePreview && (
            <div className="website-preview-section">
              <div className="preview-header">
                <h3>React Component Preview</h3>
                <p className="preview-note">Live editable React component. Edit the code and see changes instantly!</p>
              </div>
              
              <div className="preview-actions">
                <button 
                  onClick={handleCopyCode}
                  className="action-button copy-button"
                >
                  {copySuccess ? '✓ Copied!' : '📋 Copy Code'}
                </button>
                <button 
                  onClick={handleDownloadCode}
                  className="action-button download-button"
                >
                  💾 Download ZIP
                </button>
              </div>

              <div className="sandpack-container">
                <Sandpack
                  template="react"
                  theme="light"
                  files={{
                    '/App.js': websitePreview,
                    '/index.html': `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated Component</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <div id="root"></div>
</body>
</html>`,
                    '/styles.css': `/* Custom styles if needed */
body {
  margin: 0;
  padding: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
}`
                  }}
                  options={{
                    showNavigator: false,
                    showLineNumbers: true,
                    showInlineErrors: true,
                    wrapContent: true,
                    editorHeight: 600,
                    editorWidthPercentage: 50,
                    showTabs: true,
                    closableTabs: false,
                  }}
                  customSetup={{
                    dependencies: {
                      'react': '^18.2.0',
                      'react-dom': '^18.2.0'
                    },
                    entry: '/App.js'
                  }}
                />
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

export default AIPreviewGenerator

