import JSZip from 'jszip'

export const downloadPreviewCode = async (code) => {
  if (!code) return
  try {
    const zip = new JSZip()
    zip.file('App.js', code)
    zip.file('package.json', JSON.stringify({
      name: 'generated-react-component',
      version: '1.0.0',
      private: true,
      dependencies: { react: '^18.2.0', 'react-dom': '^18.2.0', 'react-scripts': '5.0.1' },
      scripts: { start: 'react-scripts start', build: 'react-scripts build' }
    }, null, 2))
    zip.file('README.md', '# Generated by Chapadevs AI\n\nnpm install\nnpm start')
    const blob = await zip.generateAsync({ type: 'blob' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'react-component.zip'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  } catch (err) {
    console.error('Failed to download', err)
  }
}
